"""In this module, we configure stuff."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_configuration.ipynb.

# %% auto #0
__all__ = ['config', 'Config', 'append_to_file']

# %% ../nbs/01_configuration.ipynb #75bc1062
from pathlib import Path
import thucy
from dotenv import set_key, load_dotenv, dotenv_values
from pydantic import BaseModel

# %% ../nbs/01_configuration.ipynb #2c1d2c62
class Config:
    """Global configuration for the thucy project"""

    DEFAULTS = {
        "EXPERTS_MODEL": "gpt-5-mini",
        "LEAD_MODEL": "gpt-5",
        "LEAD_MAX_TURNS": "40",
        "SQL_EXPERT_MAX_TURNS": "30",
        "SCHEMA_EXPERT_MAX_TURNS": "30",
        "DATA_EXPERT_MAX_TURNS": "30",
        "GENAI_SERVER_URL": "http://127.0.0.1:5000",
        "SQL_EXPERT_TOOLSET": "seattle-sql",
        "SCHEMA_EXPERT_TOOLSET": "seattle-schema",
        "DATA_EXPERT_TOOLSET": "seattle-schema",
    }
    
    def __init__(self):
        # Path Configs
        self.project_root = Path(thucy.__file__).parent.parent
        self.expertiments_dir = self.project_root / "experiments"
        self.results_dir = self.expertiments_dir / "results"  
        self.logs_dir = self.expertiments_dir / "logs" 

        self.env_path = self.project_root / ".env"
        self.env_path.touch(exist_ok=True)

        # Set defaults if not already set
        env = dotenv_values(self.env_path)
        for key, val in self.DEFAULTS.items():
            if key not in env:
                self.set_env_var(key, str(val))

        # Load environment variables
        self._load_env()

    def _load_env(self):
        """Load everything in DEFAULTS + everything in the .env file."""
        # Load into the environment to make sure
        load_dotenv(self.env_path, override=True)
        env = dotenv_values(self.env_path)

        for key, val in env.items():
            if val.isdigit(): setattr(self, key.lower(), int(val))
            else: setattr(self, key.lower(), val)
    
    def restore_defaults(self):
        for key, val in self.DEFAULTS.items():
            self.set_env_var(key, str(val))

    def set_env_var(self, key, value):
        """Set or update a variable and persist to .env."""
        set_key(self.env_path, key, str(value))
        self._load_env()

    def show_config(self):
        env = dotenv_values(self.env_path)
        for key, val in env.items():
            print(f"{key}={val}")

# %% ../nbs/01_configuration.ipynb #3b9421f3
config = Config()

# %% ../nbs/01_configuration.ipynb #51fa2a10
def append_to_file(filename: str,  # filename to append to
                   data: BaseModel,  # a Pydantic BaseModel instance with attributes to log
                   general_tag: str  # a general tag to wrap around the data
                   ):
    """ Append the attributes of a Pydantic BaseModel instance to a file within a general tag."""
    with open(config.results_dir / filename, "a", encoding="utf-8") as f:

        f.write(f"\n<{general_tag}>\n")

        for field, value in data.model_dump().items():
            f.write(f"<{field}>\n{value}\n</{field}>\n")

        f.write(f"</{general_tag}>\n")
