"""Here, we will define the main functionalities of the package."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_main.ipynb.

# %% auto #0
__all__ = ['handle_config_command', 'handle_verify_command', 'main']

# %% ../nbs/04_main.ipynb #69f03279
import argparse
from .configuration import *
from .toolbox import *
from agents import trace
from .agents import *
import asyncio
import uuid

# %% ../nbs/04_main.ipynb #40d39c4b
def handle_config_command(args):
    if args.config_action == 'set':
        config.set_env_var(args.key, args.value)
    elif args.config_action == 'show':
        config.show_config()
    else:
        print("Use: thucy config [set|show]")

# %% ../nbs/04_main.ipynb #6401a3ec
async def handle_verify_command(args):

    print("Setting up connection to Google's toolbox...")
    genai_mcp.connect()
    print("Success!")

    user_query = UserQuery(query=args.query)

    print("Starting Verification. Might take a while...!")
    with trace(args.workflow) as t:
        result = await verify(user_query)
    print("Success!")
    print(f"\nThucy Verdict: {result.verdict}\n")
    
    trace_id = t.trace_id
    file_id = f"{args.workflow}-{trace_id}"

    append_to_file(f"{file_id}.txt", user_query, "userQuery")
    append_to_file(f"{file_id}.txt", result, "verificationAnswer")

    print(f"Saved full report to experiments/results/{file_id}.txt")

    genai_mcp.close()
    print("Exiting!")

# %% ../nbs/04_main.ipynb #57cc64b5
def main():
    parser = argparse.ArgumentParser(description='Thucy CLI')

    subparsers = parser.add_subparsers(dest='command', help='Commands')

    # ---------------------------------------------
    # thucy verify "<query>" --workflow ... --toolset ...
    # ---------------------------------------------

    verify_parser = subparsers.add_parser('verify', help='Run claim verification')
    verify_parser.add_argument('query', help='Natural language query to verify')
    verify_parser.add_argument('--workflow', default=f'workflow-{uuid.uuid4().hex[:8]}',
                              help="A name that will help you find this file in the results. It is not important for it to be unique, but it would be helpful! We usually set it to something that describes the veriication 'workflow' (e.g., 'Seattle-Violent-Crime').")

    # ---------------------------------------------
    # thucy config ...
    # ---------------------------------------------
    config_parser = subparsers.add_parser('config', help='Manage configuration')
    config_subparsers = config_parser.add_subparsers(dest='config_action')

    # thucy config set KEY VALUE
    set_parser = config_subparsers.add_parser('set', help='Set a config value')
    set_parser.add_argument('key', help='Config key (e.g., OPENAI_API_KEY)')
    set_parser.add_argument('value', help='Config value')
    # thucy config list
    config_subparsers.add_parser('show', help='List available keys')
    
    args = parser.parse_args()
    
    if args.command == 'config':
        handle_config_command(args)
    elif args.command == 'verify':
        asyncio.run(handle_verify_command(args))
    else:
        parser.print_help()

# %% ../nbs/04_main.ipynb #4d895d41
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False

# %% ../nbs/04_main.ipynb #9aaeb9b9
if __name__ == '__main__' and not IN_NOTEBOOK:
    main()
