"""In this notebook, we will explore how to configure and use various tools available in Google's MCP Toolbox. These are defined in `tools.yaml` configuration file."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_toolbox.ipynb.

# %% auto 0
__all__ = ['genai_mcp', 'GenAIToolboxMCP']

# %% ../nbs/02_toolbox.ipynb 3
from toolbox_core import ToolboxSyncClient
from agents import function_tool
from .configuration import config

# %% ../nbs/02_toolbox.ipynb 4
class GenAIToolboxMCP:
    """Manager for a shared ToolboxSyncClient connection."""
    
    def __init__(self):
        self.client = None
    
    def connect(self):
        self.client = ToolboxSyncClient(config.genai_server_url)
    
    def close(self):
        if self.client:
            self.client.close()
    
    def _load_raw_toolset(self, toolset_name: str):
        """Load raw toolset from client."""
        if not self.client:
            raise RuntimeError("Call connect() first")
        return self.client.load_toolset(toolset_name)
    
    def load_toolset(self, toolset_name: str):
        """Load toolset and wrap tools for OpenAI SDK."""
        return [function_tool(tool) for tool in self._load_raw_toolset(toolset_name)]

# %% ../nbs/02_toolbox.ipynb 6
genai_mcp = GenAIToolboxMCP()
